name: JSON schema validator
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'general_schema.json'
      - 'examples/**'

jobs:
  json-schema-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r src/requirements.txt
    - name: Schema validation
      id: schema
      run: python src/schema_validator.py
    - name: Prepare schema validator comment
      if: failure()
      run: |
        echo "Validation Fails   " > comment.md; cat validation.report >> comment.md
        pwd
        ls -l
        exit 1
    - name: Prepare success comment
      run: |
        echo "Validation Passes   " > comment.md
    - name: Post comment validator comment
      if: always()
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      uses: NejcZdovc/comment-pr@v2.0.0
      with:
        file: "../../comment.md"